float snoise(float2 v)
float snoise(float3 v)
float snoise(float4 v)
float2 snoise2D(float2 v)
float3 snoise3D(float3 v)
float3 snoise_grad(float3 v)
float curlX(float3 v, float d)
float curlY(float3 v, float d)
float curlZ(float3 v, float d)
float2 CurlNoise(float2 pos, float e)
float3 CurlNoise(float3 pos, float e)
float random(float x)
float random(float2 _st)
float random(float3 _st)
float valueNoise(float2 _st)
float morganNoise(float2 _st)
float fbm2DWithMorgan(float2 _st, int numOfOctaves)
float fbmWithSimplex(float u, int numOfOctaves)
float fbmWithSimplex(float2 uv, int numOfOctaves)
float fbmWithSimplex(float3 uv, int numOfOctaves)